include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/l10n/**"
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    use_super_parameters: true
    sort_pub_dependencies: false
